### ISSUE TITLE
Create reducer for timeline

### ISSUE THREAD

**Issue by thorsteinson** [thorsteinson/commitstory#7]
We need to write a reducer for our timeline and figure our just exactly how to represent the state of our program at any point in time.

We need to decide how to store our data, as we can either compute everything ahead of time (lots of space), and then create a mapping for navigating, or compute everything on demand (lots of time). Both approaches have advantages and disadvantages but not much can be done without first deciding this structure.

**Comment by emarkovic** [comment]
lets compute ahead of time and then map for navigation
